/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HomeRouteImport } from './routes/home'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PromoRouteImport } from './routes/promo'
import { Route as SearchRouteImport } from './routes/search'
import { Route as UploadReviewRouteImport } from './routes/upload-review'
import { Route as AuthorAuthorNameRouteImport } from './routes/author.$authorName'
import { Route as BookBookIdRouteImport } from './routes/book.$bookId'
import { Route as ApiPromoVideoIdRouteImport } from './routes/api/promo-video.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PromoRoute = PromoRouteImport.update({
  id: '/promo',
  path: '/promo',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadReviewRoute = UploadReviewRouteImport.update({
  id: '/upload-review',
  path: '/upload-review',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorAuthorNameRoute = AuthorAuthorNameRouteImport.update({
  id: '/author/$authorName',
  path: '/author/$authorName',
  getParentRoute: () => rootRouteImport,
} as any)
const BookBookIdRoute = BookBookIdRouteImport.update({
  id: '/book/$bookId',
  path: '/book/$bookId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPromoVideoIdRoute = ApiPromoVideoIdRouteImport.update({
  id: '/api/promo-video/$id',
  path: '/api/promo-video/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/promo': typeof PromoRoute
  '/search': typeof SearchRoute
  '/upload-review': typeof UploadReviewRoute
  '/author/$authorName': typeof AuthorAuthorNameRoute
  '/book/$bookId': typeof BookBookIdRoute
  '/api/promo-video/$id': typeof ApiPromoVideoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/promo': typeof PromoRoute
  '/search': typeof SearchRoute
  '/upload-review': typeof UploadReviewRoute
  '/author/$authorName': typeof AuthorAuthorNameRoute
  '/book/$bookId': typeof BookBookIdRoute
  '/api/promo-video/$id': typeof ApiPromoVideoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/promo': typeof PromoRoute
  '/search': typeof SearchRoute
  '/upload-review': typeof UploadReviewRoute
  '/author/$authorName': typeof AuthorAuthorNameRoute
  '/book/$bookId': typeof BookBookIdRoute
  '/api/promo-video/$id': typeof ApiPromoVideoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/home'
    | '/onboarding'
    | '/profile'
    | '/promo'
    | '/search'
    | '/upload-review'
    | '/author/$authorName'
    | '/book/$bookId'
    | '/api/promo-video/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/home'
    | '/onboarding'
    | '/profile'
    | '/promo'
    | '/search'
    | '/upload-review'
    | '/author/$authorName'
    | '/book/$bookId'
    | '/api/promo-video/$id'
  id:
    | '__root__'
    | '/'
    | '/home'
    | '/onboarding'
    | '/profile'
    | '/promo'
    | '/search'
    | '/upload-review'
    | '/author/$authorName'
    | '/book/$bookId'
    | '/api/promo-video/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HomeRoute: typeof HomeRoute
  OnboardingRoute: typeof OnboardingRoute
  ProfileRoute: typeof ProfileRoute
  PromoRoute: typeof PromoRoute
  SearchRoute: typeof SearchRoute
  UploadReviewRoute: typeof UploadReviewRoute
  AuthorAuthorNameRoute: typeof AuthorAuthorNameRoute
  BookBookIdRoute: typeof BookBookIdRoute
  ApiPromoVideoIdRoute: typeof ApiPromoVideoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promo': {
      id: '/promo'
      path: '/promo'
      fullPath: '/promo'
      preLoaderRoute: typeof PromoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload-review': {
      id: '/upload-review'
      path: '/upload-review'
      fullPath: '/upload-review'
      preLoaderRoute: typeof UploadReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/author/$authorName': {
      id: '/author/$authorName'
      path: '/author/$authorName'
      fullPath: '/author/$authorName'
      preLoaderRoute: typeof AuthorAuthorNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$bookId': {
      id: '/book/$bookId'
      path: '/book/$bookId'
      fullPath: '/book/$bookId'
      preLoaderRoute: typeof BookBookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/promo-video/$id': {
      id: '/api/promo-video/$id'
      path: '/api/promo-video/$id'
      fullPath: '/api/promo-video/$id'
      preLoaderRoute: typeof ApiPromoVideoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HomeRoute: HomeRoute,
  OnboardingRoute: OnboardingRoute,
  ProfileRoute: ProfileRoute,
  PromoRoute: PromoRoute,
  SearchRoute: SearchRoute,
  UploadReviewRoute: UploadReviewRoute,
  AuthorAuthorNameRoute: AuthorAuthorNameRoute,
  BookBookIdRoute: BookBookIdRoute,
  ApiPromoVideoIdRoute: ApiPromoVideoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
